### ISSUE TITLE
How to connect the joints of the dual material version?

### ISSUE THREAD

**Issue by ole** [DrLex0/print3D-FlexiRex#2]
@DrLex0 Thanks for making this project available.

Apologies if this is a stupid question, but how am I supposed to connect the joints of the two 'dual' files? I printed the two files in different colors without really looking at the models first. They came out nicely, but the axles and shackles are all closed loops and seemingly impossible to link after the fact. Am I supposed to cut them open in some way? Or adjust the models before printing?

![IMG_8779](https://user-images.githubusercontent.com/5010/111157711-7dad5700-8597-11eb-82bd-93d681b834f1.jpg)

![IMG_8786](https://user-images.githubusercontent.com/5010/111157716-7ede8400-8597-11eb-8854-8e8aee6c3b7e.jpg)

**Comment by DrLex0** [comment]
Like the single-color model, the dual-color model is also supposed to be printed _in one single print job_ using a multi-material printer that can switch materials during the print. So I'm afraid those parts you printed will only be useful to demonstrate what the hinges look like from the inside.

You can make a multi-color print with a single material printer if you use the [separate parts version](https://github.com/DrLex0/print3D-flexirex-separate) of this model.

**Comment by ole** [comment]
Thanks for the reply. I definitely misunderstood this in the readme.
